NightMusicTable:
night_music: MACRO
	db \1, \2
ENDM
	night_music MUSIC_AZALEA_TOWN,       MUSIC_AZALEA_TOWN
	night_music MUSIC_LITTLEROOT_TOWN,   MUSIC_LITTLEROOT_TOWN
	night_music MUSIC_KANTO_WILD_BATTLE, MUSIC_KANTO_WILD_BATTLE
	night_music MUSIC_ROUTE_36,          MUSIC_ROUTE_36
	night_music MUSIC_ECRUTEAK_CITY,     MUSIC_ECRUTEAK_CITY
	night_music MUSIC_CHERRYGROVE_CITY,  MUSIC_CHERRYGROVE_CITY
	night_music MUSIC_VIOLET_CITY,       MUSIC_VIOLET_CITY
	night_music MUSIC_GOLDENROD_CITY,    MUSIC_GOLDENROD_CITY
	night_music MUSIC_LAVENDER_TOWN,     MUSIC_LAVENDER_TOWN
	night_music MUSIC_LAKE_OF_RAGE,      MUSIC_LAKE_OF_RAGE
	night_music MUSIC_CELADON_CITY,      MUSIC_CELADON_CITY
	night_music MUSIC_ROUTE_1,           MUSIC_ROUTE_1
	night_music MUSIC_ROUTE_3,           MUSIC_ROUTE_3
	night_music MUSIC_ROUTE_12,          MUSIC_ROUTE_12
	night_music MUSIC_ROUTE_29,          MUSIC_ROUTE_29
	night_music MUSIC_ROUTE_30,          MUSIC_ROUTE_30
	night_music MUSIC_ROUTE_37,          MUSIC_ROUTE_37
	db -1 ; end
