AnimationPointers:
	dw RowletAnimation
	dw DartrixAnimation
	dw DecidueyeAnimation
	dw TepigAnimation
	dw PigniteAnimation
	dw EmboarAnimation
	dw MudkipAnimation
	dw MarshtompAnimation
	dw SwampertAnimation
	dw PikipekAnimation
	dw TrumbeakAnimation
	dw ToucannonAnimation
	dw LillipupAnimation
	dw HerdierAnimation
	dw StoutlandAnimation
	dw VenipedeAnimation
	dw WhirlipedeAnimation
	dw ScolipedeAnimation
	dw CutieflyAnimation
	dw RibombeeAnimation
	dw SpearowAnimation
	dw FearowAnimation
	dw EkansAnimation
	dw ArbokAnimation
	dw PikachuAnimation
	dw RaichuAnimation
	dw DrilburAnimation
	dw ExcadrillAnimation
	dw SewaddleAnimation
	dw SwadloonAnimation
	dw LeavannyAnimation
	dw NidoranMAnimation
	dw NidorinoAnimation
	dw NidokingAnimation
	dw CleffaAnimation
	dw ClefairyAnimation
	dw ClefableAnimation
	dw VulpixAnimation
	dw NinetalesAnimation
	dw IgglybuffAnimation
	dw JigglypuffAnimation
	dw WigglytuffAnimation
	dw ZubatAnimation
	dw GolbatAnimation
	dw CrobatAnimation
	dw CottoneeAnimation
	dw WhimsicottAnimation
	dw PetililAnimation
	dw LilligantAnimation
	dw JoltikAnimation
	dw GalvantulaAnimation
	dw VenonatAnimation
	dw VenomothAnimation
	dw SandygastAnimation
	dw PalossandAnimation
	dw PurrloinAnimation
	dw LiepardAnimation
	dw PsyduckAnimation
	dw GolduckAnimation
	dw MankeyAnimation
	dw PrimeapeAnimation
	dw AnnihilapeAnimation
	dw GrowlitheAnimation
	dw ArcanineAnimation
	dw PoliwagAnimation
	dw PoliwhirlAnimation
	dw PoliwrathAnimation
	dw PolitoedAnimation
	dw SolosisAnimation
	dw DuosionAnimation
	dw ReuniclusAnimation
	dw TimburrAnimation
	dw GurdurrAnimation
	dw ConkeldurrAnimation
	dw BellsproutAnimation
	dw WeepinbellAnimation
	dw VictreebelAnimation
	dw TentacoolAnimation
	dw TentacruelAnimation
	dw GeodudeAnimation
	dw GravelerAnimation
	dw GolemAnimation
	dw PonytaAnimation
	dw RapidashAnimation
	dw SlowpokeAnimation
	dw SlowbroAnimation
	dw SlowkingAnimation
	dw MagnemiteAnimation
	dw MagnetonAnimation
	dw MagnezoneAnimation
	dw FarfetchDAnimation
	dw SirfetchDAnimation
	dw DoduoAnimation
	dw DodrioAnimation
	dw SeelAnimation
	dw DewgongAnimation
	dw GrimerAnimation
	dw MukAnimation
	dw MareanieAnimation
	dw ToxapexAnimation
	dw GastlyAnimation
	dw HaunterAnimation
	dw GengarAnimation
	dw OnixAnimation
	dw SteelixAnimation
	dw DrowzeeAnimation
	dw HypnoAnimation
	dw CorphishAnimation
	dw CrawdauntAnimation
	dw VoltorbAnimation
	dw ElectrodeAnimation
	dw ExeggcuteAnimation
	dw ExeggutorAnimation
	dw CuboneAnimation
	dw MarowakAnimation
	dw ScraggyAnimation
	dw ScraftyAnimation
	dw RioluAnimation
	dw LucarioAnimation
	dw LickitungAnimation
	dw LickilickyAnimation
	dw KoffingAnimation
	dw WeezingAnimation
	dw RhyhornAnimation
	dw RhydonAnimation
	dw RhyperiorAnimation
	dw HappinyAnimation
	dw ChanseyAnimation
	dw BlisseyAnimation
	dw TangelaAnimation
	dw TangrowthAnimation
	dw KangaskhanAnimation
	dw HorseaAnimation
	dw SeadraAnimation
	dw KingdraAnimation
	dw GoldeenAnimation
	dw SeakingAnimation
	dw StaryuAnimation
	dw StarmieAnimation
	dw MimeJrAnimation
	dw MrMimeAnimation
	dw ScytherAnimation
	dw ScizorAnimation
	dw SmoochumAnimation
	dw JynxAnimation
	dw ElekidAnimation
	dw ElectabuzzAnimation
	dw ElectivireAnimation
	dw MagbyAnimation
	dw MagmarAnimation
	dw MagmortarAnimation
	dw PinsirAnimation
	dw TaurosAnimation
	dw MagikarpAnimation
	dw GyaradosAnimation
	dw LaprasAnimation
	dw DittoAnimation
	dw EeveeAnimation
	dw VaporeonAnimation
	dw JolteonAnimation
	dw FlareonAnimation
	dw EspeonAnimation
	dw UmbreonAnimation
	dw LeafeonAnimation
	dw GlaceonAnimation
	dw SylveonAnimation
	dw PorygonAnimation
	dw Porygon2Animation
	dw PorygonZAnimation
	dw TirtougaAnimation
	dw CarracostaAnimation
	dw ArchenAnimation
	dw ArcheopsAnimation
	dw AerodactylAnimation
	dw MunchlaxAnimation
	dw SnorlaxAnimation
	dw ArticunoAnimation
	dw ZapdosAnimation
	dw MoltresAnimation
	dw DratiniAnimation
	dw DragonairAnimation
	dw DragoniteAnimation
	dw MewtwoAnimation
	dw MewAnimation
	dw ChikoritaAnimation
	dw BayleefAnimation
	dw MeganiumAnimation
	dw CyndaquilAnimation
	dw QuilavaAnimation
	dw TyphlosionAnimation
	dw TotodileAnimation
	dw CroconawAnimation
	dw FeraligatrAnimation
	dw SentretAnimation
	dw FurretAnimation
	dw HoothootAnimation
	dw NoctowlAnimation
	dw KarrablastAnimation
	dw EscavalierAnimation
	dw ShelmetAnimation
	dw AccelgorAnimation
	dw ChinchouAnimation
	dw LanturnAnimation
	dw TogepiAnimation
	dw TogeticAnimation
	dw TogekissAnimation
	dw NatuAnimation
	dw XatuAnimation
	dw MareepAnimation
	dw FlaaffyAnimation
	dw AmpharosAnimation
	dw AbsolAnimation
	dw MarillAnimation
	dw AzumarillAnimation
	dw BonslyAnimation
	dw SudowoodoAnimation
	dw LitwickAnimation
	dw LampentAnimation
	dw ChandelureAnimation
	dw AipomAnimation
	dw AmbipomAnimation
	dw SunkernAnimation
	dw SunfloraAnimation
	dw YanmaAnimation
	dw YanmegaAnimation
	dw WooperAnimation
	dw QuagsireAnimation
	dw MurkrowAnimation
	dw HonchkrowAnimation
	dw MisdreavusAnimation
	dw MismagiusAnimation
	dw BasculinAnimation
	dw BasclegionAnimation
	dw SkorupiAnimation
	dw DrapionAnimation
	dw GirafarigAnimation
	dw FarigirafAnimation
	dw PinecoAnimation
	dw ForretressAnimation
	dw DunsparceAnimation
	dw DudunsparsAnimation
	dw GligarAnimation
	dw GliscorAnimation
	dw SnubbullAnimation
	dw GranbullAnimation
	dw QwilfishAnimation
	dw OverqwilAnimation
	dw HeracrossAnimation
	dw SneaselAnimation
	dw WeavileAnimation
	dw TeddiursaAnimation
	dw UrsaringAnimation
	dw UrsalunaAnimation
	dw SlugmaAnimation
	dw MagcargoAnimation
	dw SwinubAnimation
	dw PiloswineAnimation
	dw MamoswineAnimation
	dw CorsolaAnimation
	dw CursolaAnimation
	dw RemoraidAnimation
	dw OctilleryAnimation
	dw OrthwormAnimation
	dw LarvestaAnimation
	dw VolcaronaAnimation
	dw SkarminiAnimation
	dw SkarmoryAnimation
	dw HoundourAnimation
	dw HoundoomAnimation
	dw PhanpyAnimation
	dw DonphanAnimation
	dw StantlerAnimation
	dw WyrdeerAnimation
	dw SmeargleAnimation
	dw MiltankAnimation
	dw KotoraAnimation
	dw RaitoraAnimation
	dw GorotoraAnimation
	dw BudewAnimation
	dw RoseliaAnimation
	dw RoseradeAnimation
	dw ElectrikeAnimation
	dw ManectricAnimation
	dw CroagunkAnimation
	dw ToxicroakAnimation
	dw SwabluAnimation
	dw AltariaAnimation
	dw DuskullAnimation
	dw DusclopsAnimation
	dw DusknoirAnimation
	dw LotadAnimation
	dw LombreAnimation
	dw LudicoloAnimation
	dw SnoruntAnimation
	dw GlalieAnimation
	dw FroslassAnimation
	dw BronzorAnimation
	dw BronzongAnimation
	dw CacneaAnimation
	dw CacturneAnimation
	dw RaltsAnimation
	dw KirliaAnimation
	dw GardevoirAnimation
	dw GalladeAnimation
	dw AronAnimation
	dw LaironAnimation
	dw AggronAnimation
	dw RaikouAnimation
	dw EnteiAnimation
	dw SuicuneAnimation
	dw LarvitarAnimation
	dw PupitarAnimation
	dw TyranitarAnimation
	dw GibleAnimation
	dw GabiteAnimation
	dw GarchompAnimation
	dw DeinoAnimation
	dw ZweilousAnimation
	dw HydreigonAnimation
	dw LugiaAnimation
	dw HoOhAnimation
	dw CelebiAnimation
	dw NownAnimation
	dw MissingnoAnimation
