BitmasksPointers:
	dw RowletBitmasks
	dw DartrixBitmasks
	dw DecidueyeBitmasks
	dw TepigBitmasks
	dw PigniteBitmasks
	dw EmboarBitmasks
	dw MudkipBitmasks
	dw MarshtompBitmasks
	dw SwampertBitmasks
	dw PikipekBitmasks
	dw TrumbeakBitmasks
	dw ToucannonBitmasks
	dw LillipupBitmasks
	dw HerdierBitmasks
	dw StoutlandBitmasks
	dw VenipedeBitmasks
	dw WhirlipedeBitmasks
	dw ScolipedeBitmasks
	dw CutieflyBitmasks
	dw RibombeeBitmasks
	dw SpearowBitmasks
	dw FearowBitmasks
	dw EkansBitmasks
	dw ArbokBitmasks
	dw PikachuBitmasks
	dw RaichuBitmasks
	dw DrilburBitmasks
	dw ExcadrillBitmasks
	dw SewaddleBitmasks
	dw SwadloonBitmasks
	dw LeavannyBitmasks
	dw NidoranMBitmasks
	dw NidorinoBitmasks
	dw NidokingBitmasks
	dw CleffaBitmasks
	dw ClefairyBitmasks
	dw ClefableBitmasks
	dw VulpixBitmasks
	dw NinetalesBitmasks
	dw IgglybuffBitmasks
	dw JigglypuffBitmasks
	dw WigglytuffBitmasks
	dw ZubatBitmasks
	dw GolbatBitmasks
	dw CrobatBitmasks
	dw CottoneeBitmasks
	dw WhimsicottBitmasks
	dw PetililBitmasks
	dw LilligantBitmasks
	dw JoltikBitmasks
	dw GalvantulaBitmasks
	dw MinccinoBitmasks
	dw CinccinoBitmasks
	dw SandygastBitmasks
	dw PalossandBitmasks
	dw PurrloinBitmasks
	dw LiepardBitmasks
	dw PsyduckBitmasks
	dw GolduckBitmasks
	dw MankeyBitmasks
	dw PrimeapeBitmasks
	dw AnnihilapeBitmasks
	dw GrowlitheBitmasks
	dw ArcanineBitmasks
	dw PoliwagBitmasks
	dw PoliwhirlBitmasks
	dw PoliwrathBitmasks
	dw PolitoedBitmasks
	dw SolosisBitmasks
	dw DuosionBitmasks
	dw ReuniclusBitmasks
	dw TimburrBitmasks
	dw GurdurrBitmasks
	dw ConkeldurrBitmasks
	dw BellsproutBitmasks
	dw WeepinbellBitmasks
	dw VictreebelBitmasks
	dw TentacoolBitmasks
	dw TentacruelBitmasks
	dw GeodudeBitmasks
	dw GravelerBitmasks
	dw GolemBitmasks
	dw PonytaBitmasks
	dw RapidashBitmasks
	dw SlowpokeBitmasks
	dw SlowbroBitmasks
	dw SlowkingBitmasks
	dw MagnemiteBitmasks
	dw MagnetonBitmasks
	dw MagnezoneBitmasks
	dw FarfetchDBitmasks
	dw SirfetchDBitmasks
	dw DoduoBitmasks
	dw DodrioBitmasks
	dw SeelBitmasks
	dw DewgongBitmasks
	dw GrimerBitmasks
	dw MukBitmasks
	dw MareanieBitmasks
	dw ToxapexBitmasks
	dw GastlyBitmasks
	dw HaunterBitmasks
	dw GengarBitmasks
	dw OnixBitmasks
	dw SteelixBitmasks
	dw DrowzeeBitmasks
	dw HypnoBitmasks
	dw CorphishBitmasks
	dw CrawdauntBitmasks
	dw VoltorbBitmasks
	dw ElectrodeBitmasks
	dw ExeggcuteBitmasks
	dw ExeggutorBitmasks
	dw CuboneBitmasks
	dw MarowakBitmasks
	dw ScraggyBitmasks
	dw ScraftyBitmasks
	dw RioluBitmasks
	dw LucarioBitmasks
	dw LickitungBitmasks
	dw LickilickyBitmasks
	dw KoffingBitmasks
	dw WeezingBitmasks
	dw RhyhornBitmasks
	dw RhydonBitmasks
	dw RhyperiorBitmasks
	dw HappinyBitmasks
	dw ChanseyBitmasks
	dw BlisseyBitmasks
	dw TangelaBitmasks
	dw TangrowthBitmasks
	dw KangaskhanBitmasks
	dw HorseaBitmasks
	dw SeadraBitmasks
	dw KingdraBitmasks
	dw GoldeenBitmasks
	dw SeakingBitmasks
	dw StaryuBitmasks
	dw StarmieBitmasks
	dw MimeJrBitmasks
	dw MrMimeBitmasks
	dw ScytherBitmasks
	dw ScizorBitmasks
	dw SmoochumBitmasks
	dw JynxBitmasks
	dw ElekidBitmasks
	dw ElectabuzzBitmasks
	dw ElectivireBitmasks
	dw MagbyBitmasks
	dw MagmarBitmasks
	dw MagmortarBitmasks
	dw PinsirBitmasks
	dw TaurosBitmasks
	dw MagikarpBitmasks
	dw GyaradosBitmasks
	dw LaprasBitmasks
	dw DittoBitmasks
	dw EeveeBitmasks
	dw VaporeonBitmasks
	dw JolteonBitmasks
	dw FlareonBitmasks
	dw EspeonBitmasks
	dw UmbreonBitmasks
	dw LeafeonBitmasks
	dw GlaceonBitmasks
	dw SylveonBitmasks
	dw PorygonBitmasks
	dw Porygon2Bitmasks
	dw PorygonZBitmasks
	dw TirtougaBitmasks
	dw CarracostaBitmasks
	dw ArchenBitmasks
	dw ArcheopsBitmasks
	dw AerodactylBitmasks
	dw MunchlaxBitmasks
	dw SnorlaxBitmasks
	dw ArticunoBitmasks
	dw ZapdosBitmasks
	dw MoltresBitmasks
	dw DratiniBitmasks
	dw DragonairBitmasks
	dw DragoniteBitmasks
	dw MewtwoBitmasks
	dw MewBitmasks
	dw ChikoritaBitmasks
	dw BayleefBitmasks
	dw MeganiumBitmasks
	dw CyndaquilBitmasks
	dw QuilavaBitmasks
	dw TyphlosionBitmasks
	dw TotodileBitmasks
	dw CroconawBitmasks
	dw FeraligatrBitmasks
	dw SentretBitmasks
	dw FurretBitmasks
	dw HoothootBitmasks
	dw NoctowlBitmasks
	dw KarrablastBitmasks
	dw EscavalierBitmasks
	dw ShelmetBitmasks
	dw AccelgorBitmasks
	dw ChinchouBitmasks
	dw LanturnBitmasks
	dw TogepiBitmasks
	dw TogeticBitmasks
	dw TogekissBitmasks
	dw NatuBitmasks
	dw XatuBitmasks
	dw MareepBitmasks
	dw FlaaffyBitmasks
	dw AmpharosBitmasks
	dw AbsolBitmasks
	dw MarillBitmasks
	dw AzumarillBitmasks
	dw BonslyBitmasks
	dw SudowoodoBitmasks
	dw LitwickBitmasks
	dw LampentBitmasks
	dw ChandelureBitmasks
	dw AipomBitmasks
	dw AmbipomBitmasks
	dw ElgyemBitmasks
	dw BeheeyemBitmasks
	dw YanmaBitmasks
	dw YanmegaBitmasks
	dw WooperBitmasks
	dw ClodsireBitmasks
	dw MurkrowBitmasks
	dw HonchkrowBitmasks
	dw MisdreavusBitmasks
	dw MismagiusBitmasks
	dw BasculinBitmasks
	dw BasclegionBitmasks
	dw SkorupiBitmasks
	dw DrapionBitmasks
	dw GirafarigBitmasks
	dw FarigirafBitmasks
	dw FerroseedBitmasks
	dw FerrothornBitmasks
	dw DunsparceBitmasks
	dw DudunsparsBitmasks
	dw GligarBitmasks
	dw GliscorBitmasks
	dw SnubbullBitmasks
	dw GranbullBitmasks
	dw QwilfishBitmasks
	dw OverqwilBitmasks
	dw HeracrossBitmasks
	dw SneaselBitmasks
	dw WeavileBitmasks
	dw TeddiursaBitmasks
	dw UrsaringBitmasks
	dw UrsalunaBitmasks
	dw SlugmaBitmasks
	dw MagcargoBitmasks
	dw SwinubBitmasks
	dw PiloswineBitmasks
	dw MamoswineBitmasks
	dw CorsolaBitmasks
	dw CursolaBitmasks
	dw RemoraidBitmasks
	dw OctilleryBitmasks
	dw OrthwormBitmasks
	dw LarvestaBitmasks
	dw VolcaronaBitmasks
	dw SkarminiBitmasks
	dw SkarmoryBitmasks
	dw HoundourBitmasks
	dw HoundoomBitmasks
	dw PhanpyBitmasks
	dw DonphanBitmasks
	dw StantlerBitmasks
	dw WyrdeerBitmasks
	dw BouffalantBitmasks
	dw MiltankBitmasks
	dw KotoraBitmasks
	dw RaitoraBitmasks
	dw GorotoraBitmasks
	dw BudewBitmasks
	dw RoseliaBitmasks
	dw RoseradeBitmasks
	dw ElectrikeBitmasks
	dw ManectricBitmasks
	dw CroagunkBitmasks
	dw ToxicroakBitmasks
	dw SwabluBitmasks
	dw AltariaBitmasks
	dw DuskullBitmasks
	dw DusclopsBitmasks
	dw DusknoirBitmasks
	dw LotadBitmasks
	dw LombreBitmasks
	dw LudicoloBitmasks
	dw SnoruntBitmasks
	dw GlalieBitmasks
	dw FroslassBitmasks
	dw BronzorBitmasks
	dw BronzongBitmasks
	dw CacneaBitmasks
	dw CacturneBitmasks
	dw RaltsBitmasks
	dw KirliaBitmasks
	dw GardevoirBitmasks
	dw GalladeBitmasks
	dw AronBitmasks
	dw LaironBitmasks
	dw AggronBitmasks
	dw AxewBitmasks
	dw FraxureBitmasks
	dw HaxorusBitmasks
	dw LarvitarBitmasks
	dw PupitarBitmasks
	dw TyranitarBitmasks
	dw GibleBitmasks
	dw GabiteBitmasks
	dw GarchompBitmasks
	dw DeinoBitmasks
	dw ZweilousBitmasks
	dw HydreigonBitmasks
	dw LugiaBitmasks
	dw HoOhBitmasks
	dw CelebiBitmasks
	dw NownBitmasks
	dw MissingnoBitmasks
