FramesPointers:
	dba RowletFrames
	dba DartrixFrames
	dba DecidueyeFrames
	dba TepigFrames
	dba PigniteFrames
	dba EmboarFrames
	dba MudkipFrames
	dba MarshtompFrames
	dba SwampertFrames
	dba PikipekFrames
	dba TrumbeakFrames
	dba ToucannonFrames
	dba LillipupFrames
	dba HerdierFrames
	dba StoutlandFrames
	dba VenipedeFrames
	dba WhirlipedeFrames
	dba ScolipedeFrames
	dba CutieflyFrames
	dba RibombeeFrames
	dba SpearowFrames
	dba FearowFrames
	dba EkansFrames
	dba ArbokFrames
	dba PikachuFrames
	dba RaichuFrames
	dba DrilburFrames
	dba ExcadrillFrames
	dba SewaddleFrames
	dba SwadloonFrames
	dba LeavannyFrames
	dba NidoranMFrames
	dba NidorinoFrames
	dba NidokingFrames
	dba CleffaFrames
	dba ClefairyFrames
	dba ClefableFrames
	dba VulpixFrames
	dba NinetalesFrames
	dba IgglybuffFrames
	dba JigglypuffFrames
	dba WigglytuffFrames
	dba ZubatFrames
	dba GolbatFrames
	dba CrobatFrames
	dba CottoneeFrames
	dba WhimsicottFrames
	dba PetililFrames
	dba LilligantFrames
	dba JoltikFrames
	dba GalvantulaFrames
	dba MinccinoFrames
	dba CinccinoFrames
	dba SandygastFrames
	dba PalossandFrames
	dba PurrloinFrames
	dba LiepardFrames
	dba PsyduckFrames
	dba GolduckFrames
	dba MankeyFrames
	dba PrimeapeFrames
	dba AnnihilapeFrames
	dba GrowlitheFrames
	dba ArcanineFrames
	dba PoliwagFrames
	dba PoliwhirlFrames
	dba PoliwrathFrames
	dba PolitoedFrames
	dba SolosisFrames
	dba DuosionFrames
	dba ReuniclusFrames
	dba TimburrFrames
	dba GurdurrFrames
	dba ConkeldurrFrames
	dba BellsproutFrames
	dba WeepinbellFrames
	dba VictreebelFrames
	dba TentacoolFrames
	dba TentacruelFrames
	dba GeodudeFrames
	dba GravelerFrames
	dba GolemFrames
	dba PonytaFrames
	dba RapidashFrames
	dba SlowpokeFrames
	dba SlowbroFrames
	dba SlowkingFrames
	dba MagnemiteFrames
	dba MagnetonFrames
	dba MagnezoneFrames
	dba FarfetchDFrames
	dba SirfetchDFrames
	dba DoduoFrames
	dba DodrioFrames
	dba SeelFrames
	dba DewgongFrames
	dba GrimerFrames
	dba MukFrames
	dba MareanieFrames
	dba ToxapexFrames
	dba GastlyFrames
	dba HaunterFrames
	dba GengarFrames
	dba OnixFrames
	dba SteelixFrames
	dba DrowzeeFrames
	dba HypnoFrames
	dba CorphishFrames
	dba CrawdauntFrames
	dba VoltorbFrames
	dba ElectrodeFrames
	dba ExeggcuteFrames
	dba ExeggutorFrames
	dba CuboneFrames
	dba MarowakFrames
	dba ScraggyFrames
	dba ScraftyFrames
	dba RioluFrames
	dba LucarioFrames
	dba LickitungFrames
	dba LickilickyFrames
	dba KoffingFrames
	dba WeezingFrames
	dba RhyhornFrames
	dba RhydonFrames
	dba RhyperiorFrames
	dba HappinyFrames
	dba ChanseyFrames
	dba BlisseyFrames
	dba TangelaFrames
	dba TangrowthFrames
	dba KangaskhanFrames
	dba HorseaFrames
	dba SeadraFrames
	dba KingdraFrames
	dba GoldeenFrames
	dba SeakingFrames
	dba StaryuFrames
	dba StarmieFrames
	dba MimeJrFrames
	dba MrMimeFrames
	dba ScytherFrames
	dba ScizorFrames
	dba SmoochumFrames
	dba JynxFrames
	dba ElekidFrames
	dba ElectabuzzFrames
	dba ElectivireFrames
	dba MagbyFrames
	dba MagmarFrames
	dba MagmortarFrames
	dba PinsirFrames
	dba TaurosFrames
	dba MagikarpFrames
	dba GyaradosFrames
	dba LaprasFrames
	dba DittoFrames
	dba EeveeFrames
	dba VaporeonFrames
	dba JolteonFrames
	dba FlareonFrames
	dba EspeonFrames
	dba UmbreonFrames
	dba LeafeonFrames
	dba GlaceonFrames
	dba SylveonFrames
	dba PorygonFrames
	dba Porygon2Frames
	dba PorygonZFrames
	dba TirtougaFrames
	dba CarracostaFrames
	dba ArchenFrames
	dba ArcheopsFrames
	dba AerodactylFrames
	dba MunchlaxFrames
	dba SnorlaxFrames
	dba ArticunoFrames
	dba ZapdosFrames
	dba MoltresFrames
	dba DratiniFrames
	dba DragonairFrames
	dba DragoniteFrames
	dba MewtwoFrames
	dba MewFrames
	dba ChikoritaFrames
	dba BayleefFrames
	dba MeganiumFrames
	dba CyndaquilFrames
	dba QuilavaFrames
	dba TyphlosionFrames
	dba TotodileFrames
	dba CroconawFrames
	dba FeraligatrFrames
	dba SentretFrames
	dba FurretFrames
	dba HoothootFrames
	dba NoctowlFrames
	dba KarrablastFrames
	dba EscavalierFrames
	dba ShelmetFrames
	dba AccelgorFrames
	dba ChinchouFrames
	dba LanturnFrames
	dba TogepiFrames
	dba TogeticFrames
	dba TogekissFrames
	dba NatuFrames
	dba XatuFrames
	dba MareepFrames
	dba FlaaffyFrames
	dba AmpharosFrames
	dba AbsolFrames
	dba MarillFrames
	dba AzumarillFrames
	dba BonslyFrames
	dba SudowoodoFrames
	dba LitwickFrames
	dba LampentFrames
	dba ChandelureFrames
	dba AipomFrames
	dba AmbipomFrames
	dba SunkernFrames
	dba SunfloraFrames
	dba YanmaFrames
	dba YanmegaFrames
	dba WooperFrames
	dba QuagsireFrames
	dba MurkrowFrames
	dba HonchkrowFrames
	dba MisdreavusFrames
	dba MismagiusFrames
	dba BasculinFrames
	dba BasclegionFrames
	dba SkorupiFrames
	dba DrapionFrames
	dba GirafarigFrames
	dba FarigirafFrames
	dba PinecoFrames
	dba ForretressFrames
	dba DunsparceFrames
	dba DudunsparsFrames
	dba GligarFrames
	dba GliscorFrames
	dba SnubbullFrames
	dba GranbullFrames
	dba QwilfishFrames
	dba OverqwilFrames
	dba HeracrossFrames
	dba SneaselFrames
	dba WeavileFrames
	dba TeddiursaFrames
	dba UrsaringFrames
	dba UrsalunaFrames
	dba SlugmaFrames
	dba MagcargoFrames
	dba SwinubFrames
	dba PiloswineFrames
	dba MamoswineFrames
	dba CorsolaFrames
	dba CursolaFrames
	dba RemoraidFrames
	dba OctilleryFrames
	dba OrthwormFrames
	dba LarvestaFrames
	dba VolcaronaFrames
	dba SkarminiFrames
	dba SkarmoryFrames
	dba HoundourFrames
	dba HoundoomFrames
	dba PhanpyFrames
	dba DonphanFrames
	dba StantlerFrames
	dba WyrdeerFrames
	dba BouffalantFrames
	dba MiltankFrames
	dba KotoraFrames
	dba RaitoraFrames
	dba GorotoraFrames
	dba BudewFrames
	dba RoseliaFrames
	dba RoseradeFrames
	dba ElectrikeFrames
	dba ManectricFrames
	dba CroagunkFrames
	dba ToxicroakFrames
	dba SwabluFrames
	dba AltariaFrames
	dba DuskullFrames
	dba DusclopsFrames
	dba DusknoirFrames
	dba LotadFrames
	dba LombreFrames
	dba LudicoloFrames
	dba SnoruntFrames
	dba GlalieFrames
	dba FroslassFrames
	dba BronzorFrames
	dba BronzongFrames
	dba CacneaFrames
	dba CacturneFrames
	dba RaltsFrames
	dba KirliaFrames
	dba GardevoirFrames
	dba GalladeFrames
	dba AronFrames
	dba LaironFrames
	dba AggronFrames
	dba AxewFrames
	dba FraxureFrames
	dba HaxorusFrames
	dba LarvitarFrames
	dba PupitarFrames
	dba TyranitarFrames
	dba GibleFrames
	dba GabiteFrames
	dba GarchompFrames
	dba DeinoFrames
	dba ZweilousFrames
	dba HydreigonFrames
	dba LugiaFrames
	dba HoOhFrames
	dba CelebiFrames
	dba NownFrames
	dba MissingnoFrames
