AnimationIdlePointers:
	dw RowletAnimationIdle
	dw DartrixAnimationIdle
	dw DecidueyeAnimationIdle
	dw TepigAnimationIdle
	dw PigniteAnimationIdle
	dw EmboarAnimationIdle
	dw MudkipAnimationIdle
	dw MarshtompAnimationIdle
	dw SwampertAnimationIdle
	dw PikipekAnimationIdle
	dw TrumbeakAnimationIdle
	dw ToucannonAnimationIdle
	dw LillipupAnimationIdle
	dw HerdierAnimationIdle
	dw StoutlandAnimationIdle
	dw VenipedeAnimationIdle
	dw WhirlipedeAnimationIdle
	dw ScolipedeAnimationIdle
	dw CutieflyAnimationIdle
	dw RibombeeAnimationIdle
	dw SpearowAnimationIdle
	dw FearowAnimationIdle
	dw EkansAnimationIdle
	dw ArbokAnimationIdle
	dw PichuAnimationIdle
	dw PikachuAnimationIdle
	dw RaichuAnimationIdle
	dw DrilburAnimationIdle
	dw ExcadrillAnimationIdle
	dw NidoranFAnimationIdle
	dw NidorinaAnimationIdle
	dw NidoqueenAnimationIdle
	dw NidoranMAnimationIdle
	dw NidorinoAnimationIdle
	dw NidokingAnimationIdle
	dw CleffaAnimationIdle
	dw ClefairyAnimationIdle
	dw ClefableAnimationIdle
	dw VulpixAnimationIdle
	dw NinetalesAnimationIdle
	dw IgglybuffAnimationIdle
	dw JigglypuffAnimationIdle
	dw WigglytuffAnimationIdle
	dw ZubatAnimationIdle
	dw GolbatAnimationIdle
	dw CrobatAnimationIdle
	dw CottoneeAnimationIdle
	dw WhimsicottAnimationIdle
	dw PetililAnimationIdle
	dw LilligantAnimationIdle
	dw ParasAnimationIdle
	dw ParasectAnimationIdle
	dw VenonatAnimationIdle
	dw VenomothAnimationIdle
	dw SandygastAnimationIdle
	dw PalossandAnimationIdle
	dw MeowthAnimationIdle
	dw PersianAnimationIdle
	dw PsyduckAnimationIdle
	dw GolduckAnimationIdle
	dw MankeyAnimationIdle
	dw PrimeapeAnimationIdle
	dw AnnihilapeAnimationIdle
	dw GrowlitheAnimationIdle
	dw ArcanineAnimationIdle
	dw PoliwagAnimationIdle
	dw PoliwhirlAnimationIdle
	dw PoliwrathAnimationIdle
	dw PolitoedAnimationIdle
	dw AbraAnimationIdle
	dw KadabraAnimationIdle
	dw AlakazamAnimationIdle
	dw MachopAnimationIdle
	dw MachokeAnimationIdle
	dw MachampAnimationIdle
	dw BellsproutAnimationIdle
	dw WeepinbellAnimationIdle
	dw VictreebelAnimationIdle
	dw TentacoolAnimationIdle
	dw TentacruelAnimationIdle
	dw GeodudeAnimationIdle
	dw GravelerAnimationIdle
	dw GolemAnimationIdle
	dw PonytaAnimationIdle
	dw RapidashAnimationIdle
	dw SlowpokeAnimationIdle
	dw SlowbroAnimationIdle
	dw SlowkingAnimationIdle
	dw MagnemiteAnimationIdle
	dw MagnetonAnimationIdle
	dw MagnezoneAnimationIdle
	dw FarfetchDAnimationIdle
	dw DoduoAnimationIdle
	dw DodrioAnimationIdle
	dw SeelAnimationIdle
	dw DewgongAnimationIdle
	dw GrimerAnimationIdle
	dw MukAnimationIdle
	dw MareanieAnimationIdle
	dw ToxapexAnimationIdle
	dw GastlyAnimationIdle
	dw HaunterAnimationIdle
	dw GengarAnimationIdle
	dw OnixAnimationIdle
	dw SteelixAnimationIdle
	dw DrowzeeAnimationIdle
	dw HypnoAnimationIdle
	dw CorphishAnimationIdle
	dw CrawdauntAnimationIdle
	dw VoltorbAnimationIdle
	dw ElectrodeAnimationIdle
	dw ExeggcuteAnimationIdle
	dw ExeggutorAnimationIdle
	dw CuboneAnimationIdle
	dw MarowakAnimationIdle
	dw ScraggyAnimationIdle
	dw ScraftyAnimationIdle
	dw RioluAnimationIdle
	dw LucarioAnimationIdle
	dw LickitungAnimationIdle
	dw LickilickyAnimationIdle
	dw KoffingAnimationIdle
	dw WeezingAnimationIdle
	dw RhyhornAnimationIdle
	dw RhydonAnimationIdle
	dw RhyperiorAnimationIdle
	dw HappinyAnimationIdle
	dw ChanseyAnimationIdle
	dw BlisseyAnimationIdle
	dw TangelaAnimationIdle
	dw TangrowthAnimationIdle
	dw KangaskhanAnimationIdle
	dw HorseaAnimationIdle
	dw SeadraAnimationIdle
	dw KingdraAnimationIdle
	dw GoldeenAnimationIdle
	dw SeakingAnimationIdle
	dw StaryuAnimationIdle
	dw StarmieAnimationIdle
	dw MimeJrAnimationIdle
	dw MrMimeAnimationIdle
	dw ScytherAnimationIdle
	dw ScizorAnimationIdle
	dw SmoochumAnimationIdle
	dw JynxAnimationIdle
	dw ElekidAnimationIdle
	dw ElectabuzzAnimationIdle
	dw ElectivireAnimationIdle
	dw MagbyAnimationIdle
	dw MagmarAnimationIdle
	dw MagmortarAnimationIdle
	dw PinsirAnimationIdle
	dw TaurosAnimationIdle
	dw MagikarpAnimationIdle
	dw GyaradosAnimationIdle
	dw LaprasAnimationIdle
	dw DittoAnimationIdle
	dw EeveeAnimationIdle
	dw VaporeonAnimationIdle
	dw JolteonAnimationIdle
	dw FlareonAnimationIdle
	dw EspeonAnimationIdle
	dw UmbreonAnimationIdle
	dw LeafeonAnimationIdle
	dw GlaceonAnimationIdle
	dw SylveonAnimationIdle
	dw PorygonAnimationIdle
	dw Porygon2AnimationIdle
	dw PorygonZAnimationIdle
	dw TirtougaAnimationIdle
	dw CarracostaAnimationIdle
	dw ArchenAnimationIdle
	dw ArcheopsAnimationIdle
	dw AerodactylAnimationIdle
	dw MunchlaxAnimationIdle
	dw SnorlaxAnimationIdle
	dw ArticunoAnimationIdle
	dw ZapdosAnimationIdle
	dw MoltresAnimationIdle
	dw DratiniAnimationIdle
	dw DragonairAnimationIdle
	dw DragoniteAnimationIdle
	dw MewtwoAnimationIdle
	dw MewAnimationIdle
	dw ChikoritaAnimationIdle
	dw BayleefAnimationIdle
	dw MeganiumAnimationIdle
	dw CyndaquilAnimationIdle
	dw QuilavaAnimationIdle
	dw TyphlosionAnimationIdle
	dw TotodileAnimationIdle
	dw CroconawAnimationIdle
	dw FeraligatrAnimationIdle
	dw SentretAnimationIdle
	dw FurretAnimationIdle
	dw HoothootAnimationIdle
	dw NoctowlAnimationIdle
	dw KarrablastAnimationIdle
	dw EscavalierAnimationIdle
	dw ShelmetAnimationIdle
	dw AccelgorAnimationIdle
	dw ChinchouAnimationIdle
	dw LanturnAnimationIdle
	dw TogepiAnimationIdle
	dw TogeticAnimationIdle
	dw TogekissAnimationIdle
	dw NatuAnimationIdle
	dw XatuAnimationIdle
	dw MareepAnimationIdle
	dw FlaaffyAnimationIdle
	dw AmpharosAnimationIdle
	dw AbsolAnimationIdle
	dw MarillAnimationIdle
	dw AzumarillAnimationIdle
	dw BonslyAnimationIdle
	dw SudowoodoAnimationIdle
	dw LitwickAnimationIdle
	dw LampentAnimationIdle
	dw ChandelureAnimationIdle
	dw AipomAnimationIdle
	dw AmbipomAnimationIdle
	dw SunkernAnimationIdle
	dw SunfloraAnimationIdle
	dw YanmaAnimationIdle
	dw YanmegaAnimationIdle
	dw WooperAnimationIdle
	dw QuagsireAnimationIdle
	dw MurkrowAnimationIdle
	dw HonchkrowAnimationIdle
	dw MisdreavusAnimationIdle
	dw MismagiusAnimationIdle
	dw BasculinAnimationIdle
	dw BasclegionAnimationIdle
	dw SkorupiAnimationIdle
	dw DrapionAnimationIdle
	dw GirafarigAnimationIdle
	dw FarigirafAnimationIdle
	dw PinecoAnimationIdle
	dw ForretressAnimationIdle
	dw DunsparceAnimationIdle
	dw DudunsparsAnimationIdle
	dw GligarAnimationIdle
	dw GliscorAnimationIdle
	dw SnubbullAnimationIdle
	dw GranbullAnimationIdle
	dw QwilfishAnimationIdle
	dw ShuckleAnimationIdle
	dw HeracrossAnimationIdle
	dw SneaselAnimationIdle
	dw WeavileAnimationIdle
	dw TeddiursaAnimationIdle
	dw UrsaringAnimationIdle
	dw UrsalunaAnimationIdle
	dw SlugmaAnimationIdle
	dw MagcargoAnimationIdle
	dw SwinubAnimationIdle
	dw PiloswineAnimationIdle
	dw MamoswineAnimationIdle
	dw CorsolaAnimationIdle
	dw CursolaAnimationIdle
	dw RemoraidAnimationIdle
	dw OctilleryAnimationIdle
	dw OrthwormAnimationIdle
	dw LarvestaAnimationIdle
	dw VolcaronaAnimationIdle
	dw SkarminiAnimationIdle
	dw SkarmoryAnimationIdle
	dw HoundourAnimationIdle
	dw HoundoomAnimationIdle
	dw PhanpyAnimationIdle
	dw DonphanAnimationIdle
	dw StantlerAnimationIdle
	dw WyrdeerAnimationIdle
	dw SmeargleAnimationIdle
	dw MiltankAnimationIdle
	dw KotoraAnimationIdle
	dw RaitoraAnimationIdle
	dw GorotoraAnimationIdle
	dw BudewAnimationIdle
	dw RoseliaAnimationIdle
	dw RoseradeAnimationIdle
	dw ElectrikeAnimationIdle
	dw ManectricAnimationIdle
	dw CroagunkAnimationIdle
	dw ToxicroakAnimationIdle
	dw SwabluAnimationIdle
	dw AltariaAnimationIdle
	dw DuskullAnimationIdle
	dw DusclopsAnimationIdle
	dw DusknoirAnimationIdle
	dw LotadAnimationIdle
	dw LombreAnimationIdle
	dw LudicoloAnimationIdle
	dw SnoruntAnimationIdle
	dw GlalieAnimationIdle
	dw FroslassAnimationIdle
	dw BronzorAnimationIdle
	dw BronzongAnimationIdle
	dw CacneaAnimationIdle
	dw CacturneAnimationIdle
	dw RaltsAnimationIdle
	dw KirliaAnimationIdle
	dw GardevoirAnimationIdle
	dw GalladeAnimationIdle
	dw AronAnimationIdle
	dw LaironAnimationIdle
	dw AggronAnimationIdle
	dw RaikouAnimationIdle
	dw EnteiAnimationIdle
	dw SuicuneAnimationIdle
	dw LarvitarAnimationIdle
	dw PupitarAnimationIdle
	dw TyranitarAnimationIdle
	dw GibleAnimationIdle
	dw GabiteAnimationIdle
	dw GarchompAnimationIdle
	dw DeinoAnimationIdle
	dw ZweilousAnimationIdle
	dw HydreigonAnimationIdle
	dw LugiaAnimationIdle
	dw HoOhAnimationIdle
	dw CelebiAnimationIdle
	dw NownAnimationIdle
	dw MissingnoAnimationIdle
