UnownsFrames: ; used only for BANK(UnownsFrames)

BasculinRFrames: INCLUDE "gfx/pokemon/basculin_r/frames.asm"
BasculinBFrames: INCLUDE "gfx/pokemon/basculin_b/frames.asm"
BasculinWFrames: INCLUDE "gfx/pokemon/basculin_w/frames.asm"
UnownDFrames: INCLUDE "gfx/pokemon/basculin_w/frames.asm"
UnownEFrames: INCLUDE "gfx/pokemon/basculin_w/frames.asm"
UnownFFrames: INCLUDE "gfx/pokemon/basculin_w/frames.asm"
UnownGFrames: INCLUDE "gfx/pokemon/basculin_w/frames.asm"
UnownHFrames: INCLUDE "gfx/pokemon/basculin_w/frames.asm"
UnownIFrames: INCLUDE "gfx/pokemon/basculin_w/frames.asm"
UnownJFrames: INCLUDE "gfx/pokemon/basculin_w/frames.asm"
UnownKFrames: INCLUDE "gfx/pokemon/basculin_w/frames.asm"
UnownLFrames: INCLUDE "gfx/pokemon/basculin_w/frames.asm"
UnownMFrames: INCLUDE "gfx/pokemon/basculin_w/frames.asm"
UnownNFrames: INCLUDE "gfx/pokemon/basculin_w/frames.asm"
UnownOFrames: INCLUDE "gfx/pokemon/basculin_w/frames.asm"
UnownPFrames: INCLUDE "gfx/pokemon/basculin_w/frames.asm"
UnownQFrames: INCLUDE "gfx/pokemon/basculin_w/frames.asm"
UnownRFrames: INCLUDE "gfx/pokemon/basculin_w/frames.asm"
UnownSFrames: INCLUDE "gfx/pokemon/basculin_w/frames.asm"
UnownTFrames: INCLUDE "gfx/pokemon/basculin_w/frames.asm"
UnownUFrames: INCLUDE "gfx/pokemon/basculin_w/frames.asm"
UnownVFrames: INCLUDE "gfx/pokemon/basculin_w/frames.asm"
UnownWFrames: INCLUDE "gfx/pokemon/basculin_w/frames.asm"
UnownXFrames: INCLUDE "gfx/pokemon/basculin_w/frames.asm"
UnownYFrames: INCLUDE "gfx/pokemon/basculin_w/frames.asm"
UnownZFrames: INCLUDE "gfx/pokemon/basculin_w/frames.asm"
