UnownsFrames: ; used only for BANK(UnownsFrames)

BasculinRFrames: INCLUDE "gfx/pokemon/basculin_r/frames.asm"
BasculinBFrames: INCLUDE "gfx/pokemon/basculin_b/frames.asm"
BasculinWFrames: INCLUDE "gfx/pokemon/basculin_w/frames.asm"
UnownDFrames: INCLUDE "gfx/pokemon/unown_d/frames.asm"
UnownEFrames: INCLUDE "gfx/pokemon/unown_e/frames.asm"
UnownFFrames: INCLUDE "gfx/pokemon/unown_f/frames.asm"
UnownGFrames: INCLUDE "gfx/pokemon/unown_g/frames.asm"
UnownHFrames: INCLUDE "gfx/pokemon/unown_h/frames.asm"
UnownIFrames: INCLUDE "gfx/pokemon/unown_i/frames.asm"
UnownJFrames: INCLUDE "gfx/pokemon/unown_j/frames.asm"
UnownKFrames: INCLUDE "gfx/pokemon/unown_k/frames.asm"
UnownLFrames: INCLUDE "gfx/pokemon/unown_l/frames.asm"
UnownMFrames: INCLUDE "gfx/pokemon/unown_m/frames.asm"
UnownNFrames: INCLUDE "gfx/pokemon/unown_n/frames.asm"
UnownOFrames: INCLUDE "gfx/pokemon/unown_o/frames.asm"
UnownPFrames: INCLUDE "gfx/pokemon/unown_p/frames.asm"
UnownQFrames: INCLUDE "gfx/pokemon/unown_q/frames.asm"
UnownRFrames: INCLUDE "gfx/pokemon/unown_r/frames.asm"
UnownSFrames: INCLUDE "gfx/pokemon/unown_s/frames.asm"
UnownTFrames: INCLUDE "gfx/pokemon/unown_t/frames.asm"
UnownUFrames: INCLUDE "gfx/pokemon/unown_u/frames.asm"
UnownVFrames: INCLUDE "gfx/pokemon/unown_v/frames.asm"
UnownWFrames: INCLUDE "gfx/pokemon/unown_w/frames.asm"
UnownXFrames: INCLUDE "gfx/pokemon/unown_x/frames.asm"
UnownYFrames: INCLUDE "gfx/pokemon/unown_y/frames.asm"
UnownZFrames: INCLUDE "gfx/pokemon/unown_z/frames.asm"
